### PR TITLE
added menu.js

### PR DESCRIPTION
**Pull request by Dan094**
HELP PLEASE

### CODE REVIEW

**Comment by mattnazari** [comment]
check out ur styles. Ur justifycontent is spelled wrong.
Also justifyContent: 'left' isnt a thing.
and 
u need to wrap everything in one view

**Comment by mattnazari** [comment]
also:
cant find variable: Text
u didnt import Text

**Comment by Dan094** [comment]
> also:
> cant find variable: Text
> u didnt import Text

Ok I will add them

**Comment by mattnazari** [comment]
u cant use 'this' with useState. it only work with {component}
it comes up as an undefined object

**Comment by Dan094** [comment]
> source={{uri:'[https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Hamburger_icon.svg/1200px-Hamburger_icon.svg.png'}}](https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Hamburger_icon.svg/1200px-Hamburger_icon.svg.png'%7D%7D) />
> change this to:
> source={{uri:'[https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Hamburger_icon.svg/1200px-Hamburger_icon.svg.png'}}](https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Hamburger_icon.svg/1200px-Hamburger_icon.svg.png'%7D%7D)
> /Changed.

**Comment by mattnazari** [comment]
const [switchState, setSwitchState] = useState(false)

var msg = null;
var bg = null;
if(switchState === false){
    msg = (
        <Text>Day Mode</Text>
)
    bg = styles.day
}
if(switchState === true){
    msg = (
        <Text style={{color:"white"}}>Night Mode</Text>
    )
    bg = styles.night
}

return(
<View style={bg}>
    <Switch
    onValueChange = {(value)=>setSwitchState(value)}
    value = {switchState}
    />
    <Text>{msg}</Text>
</View>
)
};

You have to do something like this for the side bar. 
and the default display should be none and 
when u click the touchable opacity it should be
display flex

**Comment by mattnazari** [comment]
you can also do 
position absolute for the menu and give it a left of 0
and when you click the menu it changes it to like a left of -1000

**Comment by mattnazari** [comment]
import React, {useState} from 'react';
import {View, Image, Switch, Picker, Text} from 'react-native';
import styles from '../styles/MenuStyles';

const Menu = () => {


    return (
        <View style={{width:50, height:'100%'}}>
            <Image
          style={{width: 45, height: 50}}
          source={{uri:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Hamburger_icon.svg/1200px-Hamburger_icon.svg.png'}}/>
        <View style={styles.buttons}>
           <Text>Header</Text>
                <Switch style={styles.switch}/>
            <Text>Story</Text>
                <Switch style={styles.switch}/>
            <Text>Footer</Text>
                <Switch style={styles.switch}/>
        </View>

        <View>
            <Picker
                
                 style={{height: 50, width: 100}}
                
                >
                <Picker.Item label="Theme1" value="theme1" />
                <Picker.Item label="Theme2" value="theme2" />
                <Picker.Item label="Theme3" value="theme3" />
            </Picker>
        </View>
    </View>
    )
};

export default Menu;

**Pull request closed without merging**
