### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by ashlynnchen**
please review

### CODE REVIEW

**Comment by tashavithaya** [comment]
if(inputText == true){
        showInput = (
            <TextInput 
                onChangeText={(text)=>{SetInputText(text)}}
                value={titleText}
            />

**Comment by tashavithaya** [comment]
<Button
title="Edit"
onPress={()=>{SetInputText(!inputText)}}
/>

**Comment by mattnazari** [comment]
import React, {useState} from 'react';
import {View, Text, Button, TextInput} from 'react-native';
import styles from '../styles/HeaderStyles';

function Header() {
  const [titleTxt, SetTitleTxt] = useState('The Story of My Life');
  const [inputStatus, SetInputStatus] = useState(false);

  var showInputText = null;
  if (inputStatus == true) {
    showInputText = (
      <TextInput
        onChangeText={txt => {
          SetTitleTxt(txt);
        }}
        value={titleTxt}
        placeholder="The Story of My Life"
      />
    );
  } else {
    showInputText = null;
  }

  return (
    <View style={styles.bg}>
      <View style={styles.rowContainer}>
        <Text style={styles.headerTxt}>{titleTxt}</Text>
        <Button
          title="Edit"
          onPress={() => {
            SetInputStatus(!inputStatus);
          }}
        />
      </View>
      {showInputText}
    </View>
  );
}

export default Header;
 this is for header.js

**Comment by mattnazari** [comment]
import {StyleSheet} from 'react-native';

var styles = StyleSheet.create({
    day:{
        flex:1,
        alignItems:"center",
        justifyContent:"center",
        backgroundColor:"white",
    },

    night:{
        flex:1,
        alignItems:"center",
        justifyContent:"center",
        backgroundColor:"black",
    }
});

export default styles;

this is for headerStyles.js

**Comment by mattnazari** [comment]
import {StyleSheet} from 'react-native';

var styles = StyleSheet.create({
    bg:{
        flex:1,
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:'#fffebb',
        padding:20,
    },
    rowContainer:{
        flexDirection:'row'
    },
    headerText:{
        fontSize:30,
        fontWeight:'bold'
    }
})

export default styles;

this is for headerStyles.js

**Comment by ashlynnchen** [comment]
Screen Shot 2019-10-16 at 10 58 38 AM
Screen Shot 2019-10-16 at 10 58 17 AM

**Comment by ashlynnchen** [comment]
Screen Shot 2019-10-16 at 10 59 49 AM

**Comment by ashlynnchen** [comment]
Screen Shot 2019-10-16 at 11 03 30 AM

**Comment by mattnazari** [comment]
Screen Shot 2019-10-16 at 11 12 13 AM

**Pull request merged**
